name: CI

on:
 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Opa Polyce Contract.
        run: |
          chmod +x ./check-contract.sh
          ./check-contract.sh
        shell: bash
 
        
         
         
          
         
