name: CI

on:
 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Evaluate standards with OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod u+x ./opa
          ls -lrth
          result=`./opa eval -d standards/policies/ -i contract.json --data=contract.rego --format=pretty`
          
          echo "OPA eval returned : $result"
          
          if [ "$result" != "[]" ]; then
            echo "One or more policies are violated. $result"
            exit 1
          fi
